export type Locale = "ar" | "en";

/* ---------------------------------------------------------------------------
 * All site copy lives here. `ar` is written in Modern Standard Arabic (فصحى),
 * `en` mirrors it in casual English. The `ar` object defines the shape that
 * `en` must satisfy, so a missing key is a type error.
 * ------------------------------------------------------------------------- */

const ar = {
  dir: "rtl",
  langLabel: "EN",
  langAria: "التبديل إلى الإنجليزية",
  themeAria: "تبديل الوضع الداكن",
  menuAria: "القائمة",

  nav: [
    { label: "أعمالنا", href: "/#work" },
    { label: "المشاريع", href: "/work" },
    { label: "المطاعم", href: "/restaurants" },
    { label: "آلية العمل", href: "/#process" },
    { label: "آراء العملاء", href: "/#testimonials" },
    { label: "الأسئلة", href: "/#faq" },
  ],
  navCta: "ابدأ مشروعك",
  workBack: "العودة إلى الرئيسية",

  hero: {
    eyebrow: "شركة تصميم وتطوير مواقع",
    titleA: "نصنع لك موقعًا",
    titleHighlight: "يليق باسمك",
    titleB: "ويجلب لك العملاء",
    subtitle: "موقعك على الإنترنت خلال 48 ساعة",
    ctaPrimary: "ابدأ مشروعك الآن",
    ctaSecondary: "شاهد أعمالنا",
    trust: "أكثر من 100 عميل راضٍ عن خدماتنا",
  },

  stats: [
    { value: "+100", label: "مشروع منجز" },
    { value: "48h", label: "مدة التسليم" },
    { value: "4.9/5", label: "تقييم العملاء" },
    { value: "0", label: "رسوم شهرية" },
  ],

  services: [
    "تصميم واجهات",
    "تطوير ويب",
    "متاجر إلكترونية",
    "هوية بصرية",
    "تحسين محركات البحث",
    "لوحات تحكم",
    "تطبيقات ويب",
    "استضافة ودعم",
  ],

  work: {
    eyebrow: "من أعمالنا",
    title: "أعمالنا تتحدث عنا",
    sub: "نماذج من مشاريع أنجزناها لعملائنا في مجالات مختلفة.",
    soon: "قريبًا",
    visit: "زيارة الموقع",
    view: "عرض",
    viewMore: "عرض المزيد",
    pageTitle: "جميع أعمالنا",
    pageSub: "جميع المشاريع التي أنجزناها — صنِّف حسب القسم الذي يهمك.",
    empty: "ما زلنا نُعِدّ مشاريع في هذا القسم — قريبًا بإذن الله.",
    filters: [
      { key: "all", label: "الكل" },
      { key: "corp", label: "مواقع شركات" },
      { key: "store", label: "متاجر إلكترونية" },
      { key: "tourism", label: "مواقع سياحية" },
      { key: "news", label: "مواقع إخبارية" },
      { key: "portfolio", label: "بورتفوليو" },
      { key: "clinics", label: "أنظمة عيادات" },
      { key: "landing", label: "صفحات هبوط" },
      { key: "dash", label: "لوحات تحكم" },
    ],
    projects: [
      // ── مواقع شركات (شغل حقيقي أونلاين) ─────────────────────────────
      {
        key: "fiber-glass",
        title: "Shorouk Fiberglass",
        category: "corp",
        tag: "موقع شركة",
        url: "fiber-glass-factory.vercel.app",
        href: "https://fiber-glass-factory.vercel.app/",
        image: "/assets/site-fiber-glass.png",
      },
      {
        key: "eltaher-law",
        title: "El Taher Law",
        category: "corp",
        tag: "موقع شركة",
        url: "eltaher-law.com",
        href: "https://eltaher-law.com/",
        image: "/assets/site-eltaher-law.png",
      },
      {
        key: "msk-medical",
        title: "MSK Medical",
        category: "corp",
        tag: "موقع شركة",
        url: "msk-medical-laboratory.vercel.app",
        href: "https://msk-medical-laboratory.vercel.app/",
        image: "/assets/site-msk-medical.png",
      },
      {
        key: "elikhlas",
        title: "El Ikhlas",
        category: "corp",
        tag: "موقع شركة",
        url: "elikhlas-company.vercel.app",
        href: "https://elikhlas-company.vercel.app/",
        image: "/assets/site-elikhlas.png",
      },
      {
        key: "khatab",
        title: "Khatab",
        category: "corp",
        tag: "موقع شركة",
        url: "khatab-company.vercel.app",
        href: "https://khatab-company.vercel.app/",
        image: "/assets/site-khatab.png",
      },
      {
        key: "elmotahidoon",
        title: "El Motahidoon",
        category: "corp",
        tag: "موقع شركة",
        url: "elmotahidoon-elarab.vercel.app",
        href: "https://elmotahidoon-elarab.vercel.app/",
        image: "/assets/site-elmotahidoon.png",
      },
      {
        key: "elmotahida",
        title: "El Motahida",
        category: "corp",
        tag: "موقع شركة",
        url: "elmotahida-nine.vercel.app",
        href: "https://elmotahida-nine.vercel.app/",
        image: "/assets/site-elmotahida.png",
      },
      {
        key: "canal-solar",
        title: "Canal Solar",
        category: "corp",
        tag: "موقع شركة",
        url: "canal-solar.vercel.app",
        href: "https://canal-solar.vercel.app/",
        image: "/assets/site-canal-solar.png",
      },
      {
        key: "zamzam",
        title: "Zamzam",
        category: "corp",
        tag: "موقع شركة",
        url: "zamzam-company.vercel.app",
        href: "https://zamzam-company.vercel.app/",
        image: "/assets/site-zamzam.png",
      },
      {
        key: "ms-group",
        title: "MS Group",
        category: "corp",
        tag: "موقع شركة",
        url: "ms-group-beryl.vercel.app",
        href: "https://ms-group-beryl.vercel.app/",
        image: "/assets/site-ms-group.png",
      },
      {
        key: "lovat-travels",
        title: "Lovat Travels",
        category: "corp",
        tag: "موقع شركة",
        url: "travels-lovat.vercel.app",
        href: "https://travels-lovat.vercel.app/",
        image: "/assets/site-lovat-travels.png",
      },

      // ── مواقع سياحية (شغل حقيقي أونلاين) ────────────────────────────
      {
        key: "go-sharm",
        title: "Go Sharm",
        category: "tourism",
        tag: "موقع سياحي",
        url: "escursioni-go-sharm.com",
        href: "https://escursioni-go-sharm.com/",
        image: "/assets/site-go-sharm.png",
      },

      // ── بورتفوليو (شغل حقيقي أونلاين) ───────────────────────────────
      {
        key: "hassanmohamed",
        title: "Hassan Mohamed",
        category: "portfolio",
        tag: "بورتفوليو",
        url: "hassanmohamed.online",
        href: "https://hassanmohamed.online/",
        image: "/assets/site-hassanmohamed.png",
      },

      // ── متاجر إلكترونية (شغل حقيقي أونلاين) ─────────────────────────
      {
        key: "delta-pumps",
        title: "Delta Pumps",
        category: "store",
        tag: "متجر إلكتروني",
        url: "delta-pumps.vercel.app",
        href: "https://delta-pumps.vercel.app/",
        image: "/assets/site-delta-pumps.png",
      },
      {
        key: "madinty-ratan",
        title: "Madinty Ratan",
        category: "store",
        tag: "متجر إلكتروني",
        url: "madinty-ratan.vercel.app",
        href: "https://madinty-ratan.vercel.app/",
        image: "/assets/site-madinty-ratan.png",
      },
      {
        key: "zahra",
        title: "Zahra Store",
        category: "store",
        tag: "متجر إلكتروني",
        url: "zahra-store-fawn.vercel.app",
        href: "https://zahra-store-fawn.vercel.app/",
        image: "/assets/site-zahra.png",
      },
      {
        key: "total-store",
        title: "Total Store",
        category: "store",
        tag: "متجر إلكتروني",
        url: "total-store.vercel.app",
        href: "https://total-store.vercel.app/",
        image: "/assets/site-total-store.png",
      },
      {
        key: "five-kids",
        title: "Five Kids Wear",
        category: "store",
        tag: "متجر إلكتروني",
        url: "five-kids-wear.vercel.app",
        href: "https://five-kids-wear.vercel.app/",
        image: "/assets/site-five-kids.png",
      },

      // ── متاجر إلكترونية (تصاميم جاهزة — قريباً أونلاين) ─────────────
      {
        key: "store-fashion",
        title: "Fashion Store",
        category: "store",
        tag: "متجر إلكتروني",
        image: "/assets/Fashion E-commerce.png",
      },
      {
        key: "store-beauty",
        title: "Beauty & Skincare",
        category: "store",
        tag: "متجر إلكتروني",
        image: "/assets/Beauty & Skincare.png",
      },
      {
        key: "store-electronics",
        title: "Electronics Store",
        category: "store",
        tag: "متجر إلكتروني",
        image: "/assets/Electronics E-commerce.png",
      },
      {
        key: "store-smart-home",
        title: "Smart Home",
        category: "store",
        tag: "متجر إلكتروني",
        image: "/assets/Smart Home.png",
      },
      {
        key: "store-home-decor",
        title: "Home Decor",
        category: "store",
        tag: "متجر إلكتروني",
        image: "/assets/Home Decor E-commerce.png",
      },
      {
        key: "store-sportswear",
        title: "Sportswear",
        category: "store",
        tag: "متجر إلكتروني",
        image: "/assets/Sportswear.png",
      },
      {
        key: "store-automotive",
        title: "Automotive Accessories",
        category: "store",
        tag: "متجر إلكتروني",
        image: "/assets/Automotive Accessories E-commerce.png",
      },
      {
        key: "store-pet",
        title: "Pet Supplies",
        category: "store",
        tag: "متجر إلكتروني",
        image: "/assets/Pet Supplies.png",
      },
      {
        key: "store-outdoor",
        title: "Outdoor & Camping",
        category: "store",
        tag: "متجر إلكتروني",
        image: "/assets/Outdoor & Camping.png",
      },
    ],
  },

  process: {
    eyebrow: "كيف نعمل",
    titleA: "بسيط",
    titleHighlight: "وسريع",
    sub: "ثلاث خطوات فقط ويصبح موقعك جاهزًا.",
    steps: [
      {
        n: "01",
        title: "تواصل معنا عبر واتساب",
        body: "نستمع إلى فكرتك ونفهم هدفك، ثم نضع لك خطة واضحة تناسب نشاطك وميزانيتك.",
      },
      {
        n: "02",
        title: "نبدأ التصميم والتطوير",
        body: "يبدأ الفريق بتصميم موقعك وبنائه بأحدث التقنيات وبأعلى جودة وأداء.",
      },
      {
        n: "03",
        title: "موقعك على الإنترنت خلال 48 ساعة",
        body: "يصبح موقعك جاهزًا على الإنترنت لتجذب من خلاله العملاء من اليوم الأول.",
      },
    ],
  },

  testimonials: {
    eyebrow: "آراء العملاء",
    title: "عملاء وثقوا بنا",
    sub: "آراء حقيقية من عملاء تعاملنا معهم.",
    prev: "السابق",
    next: "التالي",
    items: [
      {
        name: "محمد أيمن",
        role: "صاحب متجر إلكتروني",
        initial: "م",
        body: "جاء العمل أفضل مما تخيّلت، وأُنجز المتجر في يومين بالضبط كما اتفقنا. فريق محترم يتقن عمله.",
      },
      {
        name: "سارة خالد",
        role: "مديرة تسويق",
        initial: "س",
        body: "التصميم أنيق وبسيط، وكان ردّهم على ملاحظاتي سريعًا دون أي تعقيد. أنصح بهم بصدق.",
      },
      {
        name: "أحمد الحمدي",
        role: "صاحب شركة ناشئة",
        initial: "أ",
        body: "الفريق يفهم في التسويق لا التصميم فحسب، والنتيجة موقع سريع وجميل زاد مبيعاتنا فعلًا.",
      },
      {
        name: "منى عبد الرحمن",
        role: "صاحبة علامة ملابس",
        initial: "م",
        body: "لا أفهم شيئًا في التقنية إطلاقًا، وقد أعدّوا لي كل شيء وشرحوا لي كيف أتحكم في الموقع بنفسي.",
      },
      {
        name: "كريم فؤاد",
        role: "صاحب مطعم",
        initial: "ك",
        body: "أصبح الموقع يجلب لي طلبات من جوجل، وهو أمر لم أحققه من قبل. أموال في محلّها.",
      },
      {
        name: "نورهان سمير",
        role: "مصممة جرافيك",
        initial: "ن",
        body: "تعاملت مع كثيرين من قبل، لكنها أول مرة يسلّمني فيها أحد في الموعد بالضبط دون أعذار.",
      },
      {
        name: "مصطفى الجندي",
        role: "تاجر جملة",
        initial: "م",
        body: "سعرهم جيد جدًا مقارنة بجودة العمل. والدعم بعد التسليم فعّال حقًا لا مجرد كلام.",
      },
      {
        name: "هبة ياسر",
        role: "صاحبة مركز تعليمي",
        initial: "ه",
        body: "صمّموا لي صفحة هبوط للحملة وحقّقت نتيجة من الأسبوع الأول. الحمد لله.",
      },
      {
        name: "عمرو شعبان",
        role: "صاحب معرض سيارات",
        initial: "ع",
        body: "التواصل معهم سهل عبر واتساب ويردّون بسرعة. شعرت أنني أتعامل مع فريق يهتم بعمله.",
      },
      {
        name: "دينا مجدي",
        role: "صيدلانية",
        initial: "د",
        body: "طلبت تعديلات كثيرة فعدّلوها دون ضجر أو طلب زيادة. لهذا أرشّحهم لأصدقائي.",
      },
      {
        name: "طارق عبد الله",
        role: "مقاول",
        initial: "ط",
        body: "أصبح موقع الشركة يبدو محترمًا أمام العملاء، وقد أحدث ذلك فرقًا في الصفقات الكبيرة.",
      },
      {
        name: "ريهام فتحي",
        role: "صاحبة محل ورد",
        initial: "ر",
        body: "المتجر يعمل بشكل رائع والدفع الإلكتروني نجح من أول مرة. أنا سعيدة جدًا بصراحة.",
      },
      {
        name: "يوسف الشناوي",
        role: "مدرب عبر الإنترنت",
        initial: "ي",
        body: "أعدّوا لي نظام حجز للحصص، ووفّر عليّ وقتًا كثيرًا كنت أضيّعه في الرسائل.",
      },
      {
        name: "آية منصور",
        role: "صاحبة مشروع حرف يدوية",
        initial: "آ",
        body: "بدأت بباقة بسيطة ثم توسّعت معهم لاحقًا. فريق يسير معك خطوة بخطوة.",
      },
    ],
  },

  faq: {
    eyebrow: "الأسئلة الشائعة",
    title: "أجبنا عن سؤالك",
    items: [
      {
        q: "كم من الوقت تستغرقون لإنجاز الموقع؟",
        a: "نسلّم معظم المشاريع خلال 48 ساعة، وإن كان المشروع كبيرًا أو ذا متطلبات خاصة نُعلمك بالمدة المتوقعة قبل أن نبدأ.",
      },
      {
        q: "ما الذي أحتاج إلى تجهيزه قبل أن نبدأ؟",
        a: "اسم مشروعك ونوع نشاطك ورقم للتواصل فقط، ودع الباقي علينا.",
      },
      {
        q: "هل يمكنني طلب تعديلات بعد التسليم؟",
        a: "نعم. بعد تسليم المشروع لك 30 يومًا من التعديلات المجانية نعدّل خلالها أي شيء تحتاجه دون أي تكلفة إضافية، حتى ترضى تمامًا عن النتيجة.",
      },
      {
        q: "هل يوجد دعم بعد التسليم؟",
        a: "نعم، الدعم مستمر حتى بعد تسليم المشروع. يمكنك التواصل معنا في أي وقت وسنساعدك في حل أي مشكلة أو الرد على أي استفسار بأسرع وقت.",
      },
      {
        q: "هل يمكنني إضافة مزايا جديدة للموقع لاحقًا؟",
        a: "بالتأكيد. نصنع حلولًا مخصصة بالكامل — بوابات دفع وأنظمة حجز وربطًا مع أنظمتك الحالية. تواصل معنا ونجهّز لك باقة تناسبك.",
      },
      {
        q: "ما طريقة الدفع؟",
        a: "الدفع بعد المعاينة؛ لا تدفع أي مبلغ إلا بعد معاينة العمل أولًا.",
      },
    ],
  },

  guarantees: [
    { title: "تسليم في 48 ساعة", sub: "التزام حقيقي بالمواعيد" },
    { title: "تحسين SEO مجاني", sub: "ظهور أفضل في جوجل" },
    { title: "تصميم متجاوب 100%", sub: "يعمل على جميع الأجهزة" },
    { title: "دعم بعد التسليم", sub: "نبقى معك بعد إطلاق الموقع" },
  ],

  cta: {
    titleA: "موقعك جاهز",
    titleHighlight: "في 48 ساعة",
    sub: "ابدأ مع فيرتكس فورج اليوم — استشارة أولى مجانية دون أي التزام.",
    primary: "احجز استشارتك المجانية",
    secondary: "شاهد أعمالنا",
  },

  footer: {
    tagline: "نصنع التميّز الرقمي",
    links: [
      { label: "أعمالنا", href: "#work" },
        { label: "آراء العملاء", href: "#testimonials" },
      { label: "الأسئلة", href: "#faq" },
      { label: "تواصل معنا", href: "#contact" },
    ],
    rights: "© 2026 Vertex Forge — كل الحقوق محفوظة.",
    motto: "We Forge Digital Excellence.",
    dev: {
      prefix: "المطور",
      name: "Hassan Mohamed",
      role: "FULL STACK DEVELOPER",
      whatsappAria: "واتساب حسن محمد",
      websiteAria: "الموقع الشخصي لحسن محمد",
    },
  },

  whatsappAria: "تواصل معنا على واتساب",
};

export type Dict = typeof ar;

const en: Dict = {
  dir: "ltr",
  langLabel: "ع",
  langAria: "Switch to Arabic",
  themeAria: "Toggle dark mode",
  menuAria: "Menu",

  nav: [
    { label: "Work", href: "/#work" },
    { label: "Projects", href: "/work" },
    { label: "Restaurants", href: "/restaurants" },
    { label: "Process", href: "/#process" },
    { label: "Reviews", href: "/#testimonials" },
    { label: "FAQ", href: "/#faq" },
  ],
  navCta: "Start your project",
  workBack: "Back to home",

  hero: {
    eyebrow: "Web design & development studio",
    titleA: "We build you a site",
    titleHighlight: "worthy of your name",
    titleB: "that brings you clients",
    subtitle: "Your website live in 48 hours",
    ctaPrimary: "Start your project now",
    ctaSecondary: "See our work",
    trust: "Over 100 happy clients",
  },

  stats: [
    { value: "100+", label: "Projects delivered" },
    { value: "48h", label: "Delivery time" },
    { value: "4.9/5", label: "Client rating" },
    { value: "0", label: "Monthly fees" },
  ],

  services: [
    "UI Design",
    "Web Development",
    "E-commerce",
    "Brand Identity",
    "SEO",
    "Dashboards",
    "Web Apps",
    "Hosting & Support",
  ],

  work: {
    eyebrow: "Our work",
    title: "Our work speaks for us",
    sub: "A selection of projects we designed and built for clients across industries.",
    soon: "Soon",
    visit: "Visit site",
    view: "View",
    viewMore: "View more",
    pageTitle: "All our work",
    pageSub: "Every project we've built — filter by the category you care about.",
    empty: "We're still preparing projects for this section — coming soon.",
    filters: [
      { key: "all", label: "All" },
      { key: "corp", label: "Company sites" },
      { key: "store", label: "E-commerce" },
      { key: "tourism", label: "Tourism" },
      { key: "news", label: "News sites" },
      { key: "portfolio", label: "Portfolios" },
      { key: "clinics", label: "Clinic systems" },
      { key: "landing", label: "Landing pages" },
      { key: "dash", label: "Dashboards" },
    ],
    projects: [
      // ── Company sites (live, real work) ────────────────────────────
      {
        key: "fiber-glass",
        title: "Shorouk Fiberglass",
        category: "corp",
        tag: "Company site",
        url: "fiber-glass-factory.vercel.app",
        href: "https://fiber-glass-factory.vercel.app/",
        image: "/assets/site-fiber-glass.png",
      },
      {
        key: "eltaher-law",
        title: "El Taher Law",
        category: "corp",
        tag: "Company site",
        url: "eltaher-law.com",
        href: "https://eltaher-law.com/",
        image: "/assets/site-eltaher-law.png",
      },
      {
        key: "msk-medical",
        title: "MSK Medical",
        category: "corp",
        tag: "Company site",
        url: "msk-medical-laboratory.vercel.app",
        href: "https://msk-medical-laboratory.vercel.app/",
        image: "/assets/site-msk-medical.png",
      },
      {
        key: "elikhlas",
        title: "El Ikhlas",
        category: "corp",
        tag: "Company site",
        url: "elikhlas-company.vercel.app",
        href: "https://elikhlas-company.vercel.app/",
        image: "/assets/site-elikhlas.png",
      },
      {
        key: "khatab",
        title: "Khatab",
        category: "corp",
        tag: "Company site",
        url: "khatab-company.vercel.app",
        href: "https://khatab-company.vercel.app/",
        image: "/assets/site-khatab.png",
      },
      {
        key: "elmotahidoon",
        title: "El Motahidoon",
        category: "corp",
        tag: "Company site",
        url: "elmotahidoon-elarab.vercel.app",
        href: "https://elmotahidoon-elarab.vercel.app/",
        image: "/assets/site-elmotahidoon.png",
      },
      {
        key: "elmotahida",
        title: "El Motahida",
        category: "corp",
        tag: "Company site",
        url: "elmotahida-nine.vercel.app",
        href: "https://elmotahida-nine.vercel.app/",
        image: "/assets/site-elmotahida.png",
      },
      {
        key: "canal-solar",
        title: "Canal Solar",
        category: "corp",
        tag: "Company site",
        url: "canal-solar.vercel.app",
        href: "https://canal-solar.vercel.app/",
        image: "/assets/site-canal-solar.png",
      },
      {
        key: "zamzam",
        title: "Zamzam",
        category: "corp",
        tag: "Company site",
        url: "zamzam-company.vercel.app",
        href: "https://zamzam-company.vercel.app/",
        image: "/assets/site-zamzam.png",
      },
      {
        key: "ms-group",
        title: "MS Group",
        category: "corp",
        tag: "Company site",
        url: "ms-group-beryl.vercel.app",
        href: "https://ms-group-beryl.vercel.app/",
        image: "/assets/site-ms-group.png",
      },
      {
        key: "lovat-travels",
        title: "Lovat Travels",
        category: "corp",
        tag: "Company site",
        url: "travels-lovat.vercel.app",
        href: "https://travels-lovat.vercel.app/",
        image: "/assets/site-lovat-travels.png",
      },

      // ── Tourism sites (live, real work) ────────────────────────────
      {
        key: "go-sharm",
        title: "Go Sharm",
        category: "tourism",
        tag: "Tourism site",
        url: "escursioni-go-sharm.com",
        href: "https://escursioni-go-sharm.com/",
        image: "/assets/site-go-sharm.png",
      },

      // ── Portfolios (live, real work) ───────────────────────────────
      {
        key: "hassanmohamed",
        title: "Hassan Mohamed",
        category: "portfolio",
        tag: "Portfolio",
        url: "hassanmohamed.online",
        href: "https://hassanmohamed.online/",
        image: "/assets/site-hassanmohamed.png",
      },

      // ── E-commerce stores (live, real work) ────────────────────────
      {
        key: "delta-pumps",
        title: "Delta Pumps",
        category: "store",
        tag: "E-commerce",
        url: "delta-pumps.vercel.app",
        href: "https://delta-pumps.vercel.app/",
        image: "/assets/site-delta-pumps.png",
      },
      {
        key: "madinty-ratan",
        title: "Madinty Ratan",
        category: "store",
        tag: "E-commerce",
        url: "madinty-ratan.vercel.app",
        href: "https://madinty-ratan.vercel.app/",
        image: "/assets/site-madinty-ratan.png",
      },
      {
        key: "zahra",
        title: "Zahra Store",
        category: "store",
        tag: "E-commerce",
        url: "zahra-store-fawn.vercel.app",
        href: "https://zahra-store-fawn.vercel.app/",
        image: "/assets/site-zahra.png",
      },
      {
        key: "total-store",
        title: "Total Store",
        category: "store",
        tag: "E-commerce",
        url: "total-store.vercel.app",
        href: "https://total-store.vercel.app/",
        image: "/assets/site-total-store.png",
      },
      {
        key: "five-kids",
        title: "Five Kids Wear",
        category: "store",
        tag: "E-commerce",
        url: "five-kids-wear.vercel.app",
        href: "https://five-kids-wear.vercel.app/",
        image: "/assets/site-five-kids.png",
      },

      // ── E-commerce stores (ready designs — coming online soon) ─────
      {
        key: "store-fashion",
        title: "Fashion Store",
        category: "store",
        tag: "E-commerce",
        image: "/assets/Fashion E-commerce.png",
      },
      {
        key: "store-beauty",
        title: "Beauty & Skincare",
        category: "store",
        tag: "E-commerce",
        image: "/assets/Beauty & Skincare.png",
      },
      {
        key: "store-electronics",
        title: "Electronics Store",
        category: "store",
        tag: "E-commerce",
        image: "/assets/Electronics E-commerce.png",
      },
      {
        key: "store-smart-home",
        title: "Smart Home",
        category: "store",
        tag: "E-commerce",
        image: "/assets/Smart Home.png",
      },
      {
        key: "store-home-decor",
        title: "Home Decor",
        category: "store",
        tag: "E-commerce",
        image: "/assets/Home Decor E-commerce.png",
      },
      {
        key: "store-sportswear",
        title: "Sportswear",
        category: "store",
        tag: "E-commerce",
        image: "/assets/Sportswear.png",
      },
      {
        key: "store-automotive",
        title: "Automotive Accessories",
        category: "store",
        tag: "E-commerce",
        image: "/assets/Automotive Accessories E-commerce.png",
      },
      {
        key: "store-pet",
        title: "Pet Supplies",
        category: "store",
        tag: "E-commerce",
        image: "/assets/Pet Supplies.png",
      },
      {
        key: "store-outdoor",
        title: "Outdoor & Camping",
        category: "store",
        tag: "E-commerce",
        image: "/assets/Outdoor & Camping.png",
      },
    ],
  },

  process: {
    eyebrow: "How we work",
    titleA: "Simple",
    titleHighlight: "and fast",
    sub: "Just 3 steps and your site is ready to go.",
    steps: [
      {
        n: "01",
        title: "Message us on WhatsApp",
        body: "We listen to your idea, understand your goal, then lay out a clear plan that fits your business and budget.",
      },
      {
        n: "02",
        title: "We design and build",
        body: "Our team starts designing and building your site with the latest tech, at the highest quality and performance.",
      },
      {
        n: "03",
        title: "Live in 48 hours",
        body: "Your site goes live ready to work, so you can start bringing in clients from day one.",
      },
    ],
  },

  testimonials: {
    eyebrow: "Client reviews",
    title: "People who trusted us",
    sub: "Real feedback from clients we've worked with.",
    prev: "Previous",
    next: "Next",
    items: [
      {
        name: "Mohamed Ayman",
        role: "Online store owner",
        initial: "M",
        body: "The work came out better than I imagined, and the store was done in exactly two days as agreed. Solid people who know their craft.",
      },
      {
        name: "Sara Khaled",
        role: "Marketing manager",
        initial: "S",
        body: "Clean, modern design and they replied to all my notes fast with no runaround. Genuinely recommend them.",
      },
      {
        name: "Ahmed El-Hamdy",
        role: "Startup founder",
        initial: "A",
        body: "The team gets marketing, not just design. The result is a fast, good-looking site that actually grew our sales.",
      },
      {
        name: "Mona Abdelrahman",
        role: "Clothing brand owner",
        initial: "M",
        body: "I don't understand tech at all, and they set everything up and showed me how to manage the site myself.",
      },
      {
        name: "Karim Fouad",
        role: "Restaurant owner",
        initial: "K",
        body: "The site now brings me orders from Google, something I'd never done before. Money well spent.",
      },
      {
        name: "Nourhan Samir",
        role: "Graphic designer",
        initial: "N",
        body: "I've dealt with a lot of people before, but this is the first time someone delivered exactly on time with no excuses.",
      },
      {
        name: "Mostafa El-Gendy",
        role: "Wholesale trader",
        initial: "M",
        body: "Their price is very fair for the quality they deliver. And post-delivery support is real, not just talk.",
      },
      {
        name: "Heba Yasser",
        role: "Learning center owner",
        initial: "H",
        body: "They built me a landing page for the campaign and it brought results in the first week. Thank God.",
      },
      {
        name: "Amr Shaaban",
        role: "Car dealership owner",
        initial: "A",
        body: "Easy to reach on WhatsApp and they reply fast. Felt like dealing with people who actually care.",
      },
      {
        name: "Dina Magdy",
        role: "Pharmacist",
        initial: "D",
        body: "I asked for a lot of revisions and they did them without complaining or charging extra. That's why I recommend them to friends.",
      },
      {
        name: "Tarek Abdallah",
        role: "Contractor",
        initial: "T",
        body: "The company site looks respectable in front of clients now, and that made a difference on bigger deals.",
      },
      {
        name: "Reham Fathy",
        role: "Flower shop owner",
        initial: "R",
        body: "The store runs nicely and online payments worked the first time. Honestly very happy.",
      },
      {
        name: "Youssef El-Shennawy",
        role: "Online coach",
        initial: "Y",
        body: "They set up a booking system for my sessions and saved me hours I used to lose in messages.",
      },
      {
        name: "Aya Mansour",
        role: "Handmade business owner",
        initial: "A",
        body: "I started with a simple package and grew with them later. People who walk with you step by step.",
      },
    ],
  },

  faq: {
    eyebrow: "FAQ",
    title: "We answered your question",
    items: [
      {
        q: "How long does it take to finish the site?",
        a: "Most projects are delivered within 48 hours. If the project is large or has special requirements, we'll tell you the expected timeline before we start.",
      },
      {
        q: "What do I need to prepare before we start?",
        a: "Just your project name, your line of business, and a contact number. Leave the rest to us.",
      },
      {
        q: "Can I request changes after delivery?",
        a: "Yes. After we hand over the project you get 30 days of free revisions, during which we adjust anything you need at no extra cost, until you're 100% happy with the result.",
      },
      {
        q: "Is there support after delivery?",
        a: "Yes, support continues even after the project is delivered. Reach out any time and we'll help you solve any issue or answer any question as fast as possible.",
      },
      {
        q: "Can I add new features to the site later?",
        a: "Definitely. We build fully custom solutions — payment gateways, booking systems, integrations with your existing tools. Talk to us and we'll tailor a package for you.",
      },
    ],
  },

  guarantees: [
    { title: "48-hour delivery", sub: "A real commitment to deadlines" },
    { title: "Free SEO optimization", sub: "Better visibility on Google" },
    { title: "100% responsive design", sub: "Works on every device" },
    { title: "Post-launch support", sub: "With you after the site goes live" },
  ],

  cta: {
    titleA: "Your site is ready",
    titleHighlight: "in 48 hours",
    sub: "Start with Vertex Forge today — a free first consultation with no commitment.",
    primary: "Book your free consultation",
    secondary: "See our work",
  },

  footer: {
    tagline: "We forge digital excellence",
    links: [
      { label: "Work", href: "#work" },
        { label: "Reviews", href: "#testimonials" },
      { label: "FAQ", href: "#faq" },
      { label: "Contact", href: "#contact" },
    ],
    rights: "© 2026 Vertex Forge — All rights reserved.",
    motto: "We Forge Digital Excellence.",
    dev: {
      prefix: "developer",
      name: "Hassan Mohamed",
      role: "FULL STACK DEVELOPER",
      whatsappAria: "Hassan Mohamed on WhatsApp",
      websiteAria: "Hassan Mohamed's portfolio",
    },
  },

  whatsappAria: "Chat with us on WhatsApp",
};

export const content: Record<Locale, Dict> = { ar, en };
